# Table of Contents
 <p><div class="lev1"><a href="#Task-1.-Compiling-Ebola-Data"><span class="toc-item-num">Task 1.&nbsp;&nbsp;</span>Compiling Ebola Data</a></div>
 <div class="lev1"><a href="#Task-2.-RNA-Sequences"><span class="toc-item-num">Task 2.&nbsp;&nbsp;</span>RNA Sequences</a></div>
 <div class="lev1"><a href="#Task-3.-Class-War-in-Titanic"><span class="toc-item-num">Task 3.&nbsp;&nbsp;</span>Class War in Titanic</a></div></p>

In [7]:
DATA_FOLDER = '../../ADA2017-Tutorials-master/02 - Intro to Pandas/Data' # Use the data folder provided in Tutorial 02 - Intro to Pandas.

## Task 1. Compiling Ebola Data

The `DATA_FOLDER/ebola` folder contains summarized reports of Ebola cases from three countries (Guinea, Liberia and Sierra Leone) during the recent outbreak of the disease in West Africa. For each country, there are daily reports that contain various information about the outbreak in several cities in each country.

Use pandas to import these data files into a single `Dataframe`.
Using this `DataFrame`, calculate for *each country*, the *daily average* per year of *new cases* and *deaths*.
Make sure you handle all the different expressions for *new cases* and *deaths* that are used in the reports.

,Date,Description,Totals,File,Country
0,2014-08-04,New cases of suspects,5,../../ADA2017-Tutorials-master/02 - Intro to P...,Guinea
1,2014-08-04,New cases of probables,0,../../ADA2017-Tutorials-master/02 - Intro to P...,Guinea
2,2014-08-04,New cases of confirmed,4,../../ADA2017-Tutorials-master/02 - Intro to P...,Guinea
3,2014-08-04,Total new cases registered so far,9,../../ADA2017-Tutorials-master/02 - Intro to P...,Guinea
4,2014-08-04,Total cases of suspects,11,../../ADA2017-Tutorials-master/02 - Intro to P...,Guinea
5,2014-08-04,Total cases of probables,133,../../ADA2017-Tutorials-master/02 - Intro to P...,Guinea
6,2014-08-04,Total cases of confirmed,351,../../ADA2017-Tutorials-master/02 - Intro to P...,Guinea
7,2014-08-04,Cumulative (confirmed + probable + suspects),495,../../ADA2017-Tutorials-master/02 - Intro to P...,Guinea
8,2014-08-04,New deaths registered today,2,../../ADA2017-Tutorials-master/02 - Intro to P...,Guinea
9,2014-08-04,New deaths registered today (confirmed),2,../../ADA2017-Tutorials-master/02 - Intro to P...,Guinea
10,2014-08-04,New deaths registered today (probables),0,../../ADA2017-Tutorials-master/02 - Intro to P...,Guinea
11,2014-08-04,New deaths registered today (suspects),0,../../ADA2017-Tutorials-master/02 - Intro to P...,Guinea
12,2014-08-04,Total deaths of suspects,2,../../ADA2017-Tutorials-master/02 - Intro to P...,Guinea
13,2014-08-04,Total deaths of probables,133,../../ADA2017-Tutorials-master/02 - Intro to P...,Guinea
14,2014-08-04,Total deaths of confirmed,228,../../ADA2017-Tutorials-master/02 - Intro to P...,Guinea
15,2014-08-04,Total deaths (confirmed + probables + suspects),363,../../ADA2017-Tutorials-master/02 - Intro to P...,Guinea
16,2014-08-04,Total PEC center today,31,../../ADA2017-Tutorials-master/02 - Intro to P...,Guinea
17,2014-08-04,Total PEC center today (confirmed),18,../../ADA2017-Tutorials-master/02 - Intro to P...,Guinea
18,2014-08-04,Total PEC center today (probables),0,../../ADA2017-Tutorials-master/02 - Intro to P...,Guinea
19,2014-08-04,Total PEC center today (suspects),13,../../ADA2017-Tutorials-master/02 - Intro to P...,Guinea
20,2014-08-04,Total of deaths in confirmed cases in CTE,138,../../ADA2017-Tutorials-master/02 - Intro to P...,Guinea
21,2014-08-04,Total of cured in confirmed cases in CTE,89,../../ADA2017-Tutorials-master/02 - Intro to P...,Guinea
22,2014-08-04,Number of male confirmed cases,161,../../ADA2017-Tutorials-master/02 - Intro to P...,Guinea
23,2014-08-04,Number of female confirmed cases,190,../../ADA2017-Tutorials-master/02 - Intro to P...,Guinea
24,2014-08-04,Number of male probables cases,52,../../ADA2017-Tutorials-master/02 - Intro to P...,Guinea
25,2014-08-04,Number of female probables cases,81,../../ADA2017-Tutorials-master/02 - Intro to P...,Guinea
26,2014-08-04,Number of male suspects cases,7,../../ADA2017-Tutorials-master/02 - Intro to P...,Guinea
27,2014-08-04,Number of female suspects cases,6,../../ADA2017-Tutorials-master/02 - Intro to P...,Guinea
28,2014-08-04,Total number of male cases,220,../../ADA2017-Tutorials-master/02 - Intro to P...,Guinea
29,2014-08-04,Total number of female cases,277,../../ADA2017-Tutorials-master/02 - Intro to P...,Guinea
...,...,...,...,...,...
2,2014-10-01,New cases of confirmed,6,../../ADA2017-Tutorials-master/02 - Intro to P...,Guinea
3,2014-10-01,Total new cases registered so far,34,../../ADA2017-Tutorials-master/02 - Intro to P...,Guinea
4,2014-10-01,Total cases of suspects,45,../../ADA2017-Tutorials-master/02 - Intro to P...,Guinea
5,2014-10-01,Total cases of probables,177,../../ADA2017-Tutorials-master/02 - Intro to P...,Guinea
6,2014-10-01,Total cases of confirmed,977,../../ADA2017-Tutorials-master/02 - Intro to P...,Guinea
7,2014-10-01,Cumulative (confirmed + probable + suspects),1199,../../ADA2017-Tutorials-master/02 - Intro to P...,Guinea
8,2014-10-01,Total suspected non-class cases,974,../../ADA2017-Tutorials-master/02 - Intro to P...,Guinea
9,2014-10-01,New deaths registered,15,../../ADA2017-Tutorials-master/02 - Intro to P...,Guinea
10,2014-10-01,Total deaths of suspects,0,../../ADA2017-Tutorials-master/02 - Intro to P...,Guinea
11,2014-10-01,Total deaths of probables,177,../../ADA2017-Tutorials-master/02 - Intro to P...,Guinea
12,2014-10-01,Total deaths of confirmed,562,../../ADA2017-Tutorials-master/02 - Intro to P...,Guinea
13,2014-10-01,Total deaths (confirmed + probables + suspects),739,../../ADA2017-Tutorials-master/02 - Intro to P...,Guinea
14,2014-10-01,Fatality rate for confirmed and probables,62%,../../ADA2017-Tutorials-master/02 - Intro to P...,Guinea
15,2014-10-01,New cases of confirmed among health workers,2,../../ADA2017-Tutorials-master/02 - Intro to P...,Guinea
16,2014-10-01,Total case of confirmed among health workers,69,../../ADA2017-Tutorials-master/02 - Intro to P...,Guinea
17,2014-10-01,New deaths registered among health workers,0,../../ADA2017-Tutorials-master/02 - Intro to P...,Guinea
18,2014-10-01,Total deaths registered among health workers,35,../../ADA2017-Tutorials-master/02 - Intro to P...,Guinea
19,2014-10-01,New admits to CTE so far,25,../../ADA2017-Tutorials-master/02 - Intro to P...,Guinea
20,2014-10-01,Total number of hospitalized cases in CTE,114,../../ADA2017-Tutorials-master/02 - Intro to P...,Guinea
21,2014-10-01,Total number of exits from CTE,29,../../ADA2017-Tutorials-master/02 - Intro to P...,Guinea
22,2014-10-01,Total number of admissions to CTE,1576,../../ADA2017-Tutorials-master/02 - Intro to P...,Guinea
23,2014-10-01,New contacts registered so far,0,../../ADA2017-Tutorials-master/02 - Intro to P...,Guinea
24,2014-10-01,Total contacts registered from start date,11772,../../ADA2017-Tutorials-master/02 - Intro to P...,Guinea
25,2014-10-01,Number of contacts to follow today,2661,../../ADA2017-Tutorials-master/02 - Intro to P...,Guinea
26,2014-10-01,Number of contacts followed today,2595,../../ADA2017-Tutorials-master/02 - Intro to P...,Guinea
27,2014-10-01,Number of contacts out of the track 21 days,9110,../../ADA2017-Tutorials-master/02 - Intro to P...,Guinea
28,2014-10-01,Number of contacts lost to follow up,1,../../ADA2017-Tutorials-master/02 - Intro to P...,Guinea
29,2014-10-01,Number of samples collected today,25,../../ADA2017-Tutorials-master/02 - Intro to P...,Guinea
30,2014-10-01,Number of samples under test,0,../../ADA2017-Tutorials-master/02 - Intro to P...,Guinea
31,2014-10-01,Total samples tested,2832,../../ADA2017-Tutorials-master/02 - Intro to P...,Guinea

## Task 2. RNA Sequences

In the `DATA_FOLDER/microbiome` subdirectory, there are 9 spreadsheets of microbiome data that was acquired from high-throughput RNA sequencing procedures, along with a 10<sup>th</sup> file that describes the content of each. 

Use pandas to import the first 9 spreadsheets into a single `DataFrame`.
Then, add the metadata information from the 10<sup>th</sup> spreadsheet as columns in the combined `DataFrame`.
Make sure that the final `DataFrame` has a unique index and all the `NaN` values have been replaced by the tag `unknown`.

In [6]:
import pandas as pd
import numpy as np
import glob

# Visualization of the metadata spreadsheet

metadata = pd.read_excel("../../ADA2017-Tutorials-master/02 - Intro to Pandas/Data/microbiome/metadata.xls", 'Sheet1', index_col=0)
metadata

                      GROUP  SAMPLE
BARCODE
MID1     EXTRACTION CONTROL     NaN
MID2                  NEC 1  tissue
MID3              Control 1  tissue
MID4                  NEC 2  tissue
MID5              Control 2  tissue
MID6                  NEC 1   stool
MID7              Control 1   stool
MID8                  NEC 2   stool
MID9              Control 2   stool

In [7]:
# We import the first 9 spreadsheets

pattern = '../../ADA2017-Tutorials-master/02 - Intro to Pandas/Data/microbiome/MID*.xls'
files = glob.glob(pattern)

mid = []
for f in files :
    df = pd.read_excel(f, index_col=0, header=None)
    mid.append(df)


# We check if each file has a unique index

for i in range (metadata.shape[0]) :
    if mid[i].index.is_unique :
        print('File MID' + str(i+1) + '.xls has a unique index')
    else :
        print('File MID' + str(i+1) + '.xls does not have a unique index')

File MID1.xls has a unique index
File MID2.xls has a unique index
File MID3.xls has a unique index
File MID4.xls has a unique index
File MID5.xls has a unique index
File MID6.xls has a unique index
File MID7.xls has a unique index
File MID8.xls has a unique index
File MID9.xls has a unique index

In [8]:
# We import the first 9 spreadsheets into a single DataFrame

mid_final = pd.concat(mid, axis=1)
metadata['SAMPLE'][0] = 'Na'
mid_final.columns = [ ['Barcode: ']*9 + metadata.index + ['\n Group: ']*9 + metadata['GROUP'] + ['\nSample: ']*9 + metadata['SAMPLE']]
mid_final.columns.name = 'Count'
mid_final.index.name = 'Taxon'
mid_final.fillna('unknown', inplace = True)
mid_final.head()

Count,Barcode: MID1 Group: EXTRACTION CONTROL Sample: Na,Barcode: MID2 Group: NEC 1 Sample: tissue,Barcode: MID3 Group: Control 1 Sample: tissue,Barcode: MID4 Group: NEC 2 Sample: tissue,Barcode: MID5 Group: Control 2 Sample: tissue,Barcode: MID6 Group: NEC 1 Sample: stool,Barcode: MID7 Group: Control 1 Sample: stool,Barcode: MID8 Group: NEC 2 Sample: stool,Barcode: MID9 Group: Control 2 Sample: stool
Taxon,,,,,,,,,
"Archaea ""Crenarchaeota"" Thermoprotei Acidilobales Acidilobaceae Acidilobus",unknown,2,1,unknown,5,unknown,unknown,unknown,unknown
"Archaea ""Crenarchaeota"" Thermoprotei Acidilobales Caldisphaeraceae Caldisphaera",unknown,14,15,unknown,26,unknown,1,unknown,1
"Archaea ""Crenarchaeota"" Thermoprotei Desulfurococcales Desulfurococcaceae Ignisphaera",7,23,14,2,28,7,8,unknown,16
"Archaea ""Crenarchaeota"" Thermoprotei Desulfurococcales Desulfurococcaceae Stetteria",unknown,unknown,unknown,unknown,1,unknown,unknown,unknown,unknown
"Archaea ""Crenarchaeota"" Thermoprotei Desulfurococcales Desulfurococcaceae Sulfophobococcus",unknown,1,4,unknown,5,1,2,unknown,2

In [10]:
# We check if the dataframe has a unique index

if mid_final.index.is_unique :
    print('The dataframe has a unique index')
else :
    print('The dataframe does not have a unique index')

The dataframe has a unique index

## Task 3. Class War in Titanic

Use pandas to import the data file `Data/titanic.xls`. It contains data on all the passengers that travelled on the Titanic.

In [76]:
from IPython.core.display import HTML
HTML(filename=DATA_FOLDER+'/titanic.html')

For each of the following questions state clearly your assumptions and discuss your findings:
1. Describe the *type* and the *value range* of each attribute. Indicate and transform the attributes that can be `Categorical`. 
2. Plot histograms for the *travel class*, *embarkation port*, *sex* and *age* attributes. For the latter one, use *discrete decade intervals*. 
3. Calculate the proportion of passengers by *cabin floor*. Present your results in a *pie chart*.
4. For each *travel class*, calculate the proportion of the passengers that survived. Present your results in *pie charts*.
5. Calculate the proportion of the passengers that survived by *travel class* and *sex*. Present your results in *a single histogram*.
6. Create 2 equally populated *age categories* and calculate survival proportions by *age category*, *travel class* and *sex*. Present your results in a `DataFrame` with unique index.